version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "followupDB"
      POSTGRES_PASSWORD: "postgres"

